/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2023-05-25 01:15:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.dw.user.vo.UserVO;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/view/user/footer.jsp", Long.valueOf(1684484443758L));
    _jspx_dependants.put("/WEB-INF/view/user/header.jsp", Long.valueOf(1684976764350L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.dw.user.vo.UserVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("This is a starter template page. Use this page to start your new project from\r\n");
      out.write("scratch. This page gets rid of all links and provides the needed markup only.\r\n");
      out.write("-->\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <title>AdminLTE 3 | Starte</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("  <!-- Font Awesome Icons -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/assets/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("  <!-- Theme style -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/assets/dist/css/adminlte.min.css\">\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath());
      out.write("/assets/plugins/jquery/jquery.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("\t");

		UserVO vo = (UserVO)session.getAttribute("userVO");
	
		if(vo != null){
	
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  \t$(function(){\r\n");
      out.write("\t\t$('#loginCheck').text('Log Out');  \t\t\t\t\r\n");
      out.write("\t\t$('#loginCheck').attr('href', '");
      out.print( request.getContextPath());
      out.write("/user/userLogout.do');\r\n");
      out.write("\t\t$('#signUp').find('p').text('Profile');\r\n");
      out.write("\t\t$('#signUp').find('i').attr('class', 'nav-icon fas fa-solid fa-id-card');\r\n");
      out.write("\t\t$('#signUp').attr('href', '");
      out.print( request.getContextPath());
      out.write("/user/myPage.do');\r\n");
      out.write("  \t})\r\n");
      out.write("  </script>\r\n");
      out.write("\t");
	}	
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini\">\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("    <!-- Left navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"index3.html\" class=\"nav-link\">Home</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/userLoginForm.do\" class=\"nav-link\" id=\"loginCheck\">Log In</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/board/boardMain.do\" class=\"nav-link\">Board</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <!-- Right navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("      <!-- Navbar Search -->\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"navbar-search\" href=\"#\" role=\"button\">\r\n");
      out.write("          <i class=\"fas fa-search\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"navbar-search-block\">\r\n");
      out.write("          <form class=\"form-inline\">\r\n");
      out.write("            <div class=\"input-group input-group-sm\">\r\n");
      out.write("              <input class=\"form-control form-control-navbar\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("              <div class=\"input-group-append\">\r\n");
      out.write("                <button class=\"btn btn-navbar\" type=\"submit\">\r\n");
      out.write("                  <i class=\"fas fa-search\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"btn btn-navbar\" type=\"button\" data-widget=\"navbar-search\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      <!-- Messages Dropdown Menu -->\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("          <i class=\"far fa-comments\"></i>\r\n");
      out.write("          <span class=\"badge badge-danger navbar-badge\">3</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/assets/dist/img/user1-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 mr-3 img-circle\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  Brad Diesel\r\n");
      out.write("                  <span class=\"float-right text-sm text-danger\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">Call me whenever you can...</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/assets/dist/img/user8-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  John Pierce\r\n");
      out.write("                  <span class=\"float-right text-sm text-muted\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">I got your message bro</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/assets/dist/img/user3-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  Nora Silvester\r\n");
      out.write("                  <span class=\"float-right text-sm text-warning\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">The subject goes here</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Messages</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- Notifications Dropdown Menu -->\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("          <i class=\"far fa-bell\"></i>\r\n");
      out.write("          <span class=\"badge badge-warning navbar-badge\">15</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("          <span class=\"dropdown-header\">15 Notifications</span>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-envelope mr-2\"></i> 4 new messages\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">3 mins</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-users mr-2\"></i> 8 friend requests\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">12 hours</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-file mr-2\"></i> 3 new reports\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">2 days</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Notifications</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"fullscreen\" href=\"#\" role=\"button\">\r\n");
      out.write("          <i class=\"fas fa-expand-arrows-alt\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"control-sidebar\" data-slide=\"true\" href=\"#\" role=\"button\">\r\n");
      out.write("          <i class=\"fas fa-th-large\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- /.navbar -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Main Sidebar Container -->\r\n");
      out.write("  <aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("    <!-- Brand Logo -->\r\n");
      out.write("    <a href=\"index3.html\" class=\"brand-link\">\r\n");
      out.write("      <img src=\"");
      out.print(request.getContextPath() );
      out.write("/assets/dist/img/AdminLTELogo.png\" alt=\"AdminLTE Logo\" class=\"brand-image img-circle elevation-3\" style=\"opacity: .8\">\r\n");
      out.write("      <span class=\"brand-text font-weight-light\">AdminLTE 3</span>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("      <!-- Sidebar user panel (optional) -->\r\n");
      out.write("      <div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
      out.write("        <div class=\"image\">\r\n");
      out.write("        \r\n");
      out.write("        ");

        	String src = "/profilePath/default/defaultProfile.jpg";
        	String nick = "환영합니다.";
        
        	if(vo != null){
        		src = "/profilePath/" + vo.getPic_path();
        		nick = vo.getNick();
        	}
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("          <img src=\"");
      out.print( src );
      out.write("\" class=\"img-circle elevation-2\" alt=\"User Image\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"info\">\r\n");
      out.write("          <a href=\"#\" class=\"d-block\">");
      out.print( nick );
      out.write("</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- SidebarSearch Form -->\r\n");
      out.write("      <div class=\"form-inline\">\r\n");
      out.write("        <div class=\"input-group\" data-widget=\"sidebar-search\">\r\n");
      out.write("          <input class=\"form-control form-control-sidebar\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <button class=\"btn btn-sidebar\">\r\n");
      out.write("              <i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Sidebar Menu -->\r\n");
      out.write("      <nav class=\"mt-2\">\r\n");
      out.write("        <ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("          <!-- Add icons to the links using the .nav-icon class\r\n");
      out.write("               with font-awesome or any other icon font library -->\r\n");
      out.write("          <li class=\"nav-item menu-open\">\r\n");
      out.write("            <a href=\"#\" class=\"nav-link active\">\r\n");
      out.write("              <i class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("              <p>\r\n");
      out.write("                Starter Pages\r\n");
      out.write("                <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link active\">\r\n");
      out.write("                  <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                  <p>Active Page</p>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                  <p>Inactive Page</p>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"nav-icon fas fa-th\"></i>\r\n");
      out.write("              <p>\r\n");
      out.write("                Simple Link\r\n");
      out.write("                <span class=\"right badge badge-danger\">New</span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/joinForm.do\" class=\"nav-link\" id=\"signUp\">\r\n");
      out.write("              <i class=\"nav-icon fas fa-solid fa-user-plus\"></i>\r\n");
      out.write("              <p>\r\n");
      out.write("                Sign Up\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <!-- /.sidebar-menu -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.sidebar -->\r\n");
      out.write("  </aside>\r\n");
      out.write("\r\n");
      out.write("  <!-- Content Wrapper. Contains page content -->\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    <!-- Content Header (Page header) -->\r\n");
      out.write("    <div class=\"content-header\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row mb-2\">\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <h1 class=\"m-0\">");
      out.print( request.getAttribute("title_nm") );
      out.write(" Page</h1>\r\n");
      out.write("          </div><!-- /.col -->\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <ol class=\"breadcrumb float-sm-right\">\r\n");
      out.write("              <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("              <li class=\"breadcrumb-item active\">");
      out.print( request.getAttribute("title_nm") );
      out.write(" Page</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div><!-- /.col -->\r\n");
      out.write("        </div><!-- /.row -->\r\n");
      out.write("      </div><!-- /.container-fluid -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.content-header -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#changeSelfie').on('click', function(){\r\n");
      out.write("\t\t\t\t$('input[name=selfie]').click();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction imgFilePreview(e){\r\n");
      out.write("\t\t\t\tlet reader = new FileReader();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treader.onload = function(e){\r\n");
      out.write("\t\t\t\t\t$('#profile_picture').attr('src', e.target.result);\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treader.readAsDataURL(e.target.files[0]);\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\treadAsText - 그냥 Text 로 읽는 것. 이미지같은걸 읽으면 인코딩이 되어 있지 않으므로 깨진 내용을 반환한다.\r\n");
      out.write("\t\t\t\t\treadAsDataURL - base64로 인코딩합니다. 이미지를 다루는데 좋다.\r\n");
      out.write("\t\t\t\t\treadAsArrayBuffer - ArrayBuffer 객체를 반환한다.\r\n");
      out.write("\t\t\t\t\t\t==> buffer 니까, 데이터를 잘게 조각낸 것이고, 이를 서버에 보내서\r\n");
      out.write("\t\t\t\t\t\t\tstream으로 처리하면 된다.\r\n");
      out.write("\t\t\t\t\t\t\t영상, 오디로 등의 스트림 데이터를 다루는데 좋다.\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#saveProfileBtn').toggle();\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#selfie').on('change', imgFilePreview);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#saveProfileBtn').on('click', function(){\r\n");
      out.write("\t\t\t\tlet formData = new FormData($('#upload_form')[0]);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\tFormData를 사용하여 <form> 태그처럼 파일을 넘기는 방식을 알아보려고 한다.\r\n");
      out.write("\t\t\t\t\tdataType 은 내가 보내는 데이터의 타입이 아니고 서버가 응답(response)할 때 보내줄 데이터의 타입이다.\r\n");
      out.write("\t\t\t\t\tprocessData 관련하여, 일반적으로 서버에 전달되는 데이터는 query String 이라는 형태로 전달된다.\r\n");
      out.write("\t\t\t\t\tdata 속성의 값을 Jquery 내부적으로 query String 으로 만드는데,\r\n");
      out.write("\t\t\t\t\t파일 전송의 경우 이를 하지 않아야 하고 이를 설정하는 것이 processData : false 이다.\r\n");
      out.write("\t\t\t\t\tcontentType 은 default 값이 \"application/x-www-form-urlencoded; charset=utf-8\" 인데,\r\n");
      out.write("\t\t\t\t\t\"multipart/form-data\" 로 전송이 되게 false 로 넣어준다.\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t[요약]\r\n");
      out.write("\t\t\t\t\t- contentType : false 로 선언 시 content-type 헤더가 multipart/form-data 로 전송되게 함\r\n");
      out.write("\t\t\t\t\t- processData : flase 로 선언 시 formData를 String 으로 변환하지 않음\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/file/profilePicture.do\",\r\n");
      out.write("\t\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\t\tdata : formData,\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(res);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card card-primary card-outline\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body box-profile\">\r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"upload_form\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" id=\"changeSelfie\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"profile-user-img img-fluid img-circle\" id=\"profile_picture\" src=\"/profilePath/");
      out.print(vo.getPic_path() );
      out.write("\" alt=\"User profile picture\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" style=\"display: none;\" name=\"selfie\" id=\"selfie\" accept=\".jpg, .jpeg, .png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary btn-block\" id=\"saveProfileBtn\" style=\"display: none;\"><b>프로필 사진 저장</b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"profile-username text-center\">닉네임출력</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted text-center\">권한출력</p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-group list-group-unbordered mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>Email</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"float-right\">Email출력</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>이름</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"float-right\">이름출력</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>성별</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"float-right\">성별출력</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary btn-block\"><b>저장</b></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.content-wrapper -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Control Sidebar -->\r\n");
      out.write("  <aside class=\"control-sidebar control-sidebar-dark\">\r\n");
      out.write("    <!-- Control sidebar content goes here -->\r\n");
      out.write("    <div class=\"p-3\">\r\n");
      out.write("      <h5>Title</h5>\r\n");
      out.write("      <p>Sidebar content</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("  <!-- /.control-sidebar -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Main Footer -->\r\n");
      out.write("  <footer class=\"main-footer\">\r\n");
      out.write("    <!-- To the right -->\r\n");
      out.write("    <div class=\"float-right d-none d-sm-inline\">\r\n");
      out.write("      Anything you want\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Default to the left -->\r\n");
      out.write("    <strong>Copyright &copy; 2014-2021 <a href=\"https://adminlte.io\">AdminLTE.io</a>.</strong> All rights reserved.\r\n");
      out.write("  </footer>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- REQUIRED SCRIPTS -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/assets/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap 4 -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/assets/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/assets/dist/js/adminlte.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
